[package]
name = "rust-env"
version = "0.1.0"
edition = "2021"
authors=["TM"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3